name: Build and Push Docker Image to GHCR

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write # Required to push to GitHub Container Registry

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Log in to GitHub Container Registry
            - name: Log in to GitHub Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.LEGACY_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            # Build and push the Docker image
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  #tags: ghcr.io/${{ github.repository_owner }}/hugo-pdf-action:latest

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  draft: false
                  prerelease: false

            - name: Update latest tag
              uses: EndBug/latest-tag@latest

